
-- 1. Create 'guides' table
create table if not exists guides (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text, -- Long text / HTML
  steps jsonb, -- Same structure as errors.solutionSteps
  category text, -- Can be a foreign key or just text depending on 'errors' implementation, likely text id
  image_url text,
  image_urls text[],
  view_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create 'guide_assignees' table (Junction table)
create table if not exists guide_assignees (
  id bigint generated by default as identity primary key,
  guide_id bigint references guides(id) on delete cascade not null,
  person_id bigint references people(id) on delete cascade not null,
  unique (guide_id, person_id)
);

-- 3. Enable Row Level Security (RLS) - Optional if you are using it
-- alter table guides enable row level security;
-- alter table guide_assignees enable row level security;

-- 4. Create Policies (Example: Allow public read, auth insert/update)
-- create policy "Public guides are viewable by everyone." on guides for select using (true);
-- create policy "Authenticated users can insert guides." on guides for insert with check (true);
-- (Adjust policies as per your project's security model)
